---
- hosts: all
  become: yes
  gather_facts: false
  remote_user: root
  tasks:

  - name: Ensure python-minimal is available
    apt:
      name: python-minimal
      allow_unauthenticated: yes

  - name: Ensure python-apt is available
    apt:
      name: python-apt
      allow_unauthenticated: yes

  - name: Ensure sudo is available
    apt:
      name: sudo
      allow_unauthenticated: yes

  - name: Load packages
    apt:
      name: {{item}}
      allow_unauthenticated: yes
    with_items:
      - openjdk-11-jre-headless
      - scala

- hosts: kafka
  roles:
    - role: 'ansible-kafka'
      kafka_config_dir: "/etc/kafka"
      kafka_log_dir: "/var/log/kafka"
      kafka_data_dir: "/var/lib/kafka"
      kafka_logs_dir: "{{kafka_data_dir}}/commitlogs"
      kafka_boot_servers: "localhost:9092"
      kafka_cluster_name: "subutai"
      kafka_retention: 2160  # 90 days
