---
- hosts: [kafka]
  become: yes
  roles:
    - role: 'ansible-kafka'
      kafka_config_dir: "/etc/kafka"
      kafka_log_dir: "/var/log/kafka"
      kafka_data_dir: "/var/lib/kafka"
      kafka_logs_dir: "{{kafka_data_dir}}/commitlogs"
      kafka_boot_servers: "localhost:9092"
      kafka_cluster_name: "sensetif"
      kafka_retention: 2160  # 90 days
