---
- hosts: [kafka]
  become: yes
  roles:
    - role: 'ansible-kafka'
      kafka_config_dir: "/etc/kafka"
      kafka_log_dir: "/var/log/kafka"
      kafka_data_dir: "/var/lib/kafka"
      kafka_logs_dir: "{{kafka_data_dir}}/commitlogs"
      kafka_logs_dir_1: "{{kafka_logs_dir}}/1"
      kafka_logs_dir_2: "{{kafka_logs_dir}}/2"
      kafka_boot_servers: "kafka1.sensetif.net:9092,kafka2.sensetif.net:9092,kafka3.sensetif.net:9092"
      kafka_cluster_name: "sensetif"
      kafka_retention: 2160  # 90 days
